export const downloadData = [
  {
    id: 1,
    icon: "/file-pdf.png",
    title: "QR Code Generator",
    path: "https://high-qr-code-generator.com/",
    des: "Convert written text into spoken words.",
    tags: [{ id: "pdfs", name: "PDFs" }],
  },
  {
    id: 2,
    icon: "/file-pdf.png",
    title: "Color Palette Generator",
    path: "https://coolors.co/",
    des: "Convert written text into spoken words.",
    tags: [{ id: "pdfs", name: "PDFs" }],
  },
  {
    id: 3,
    icon: "/images.png",
    title: "HTML Formatter",
    path: "https://htmlformatter.com/",
    des: "Convert written text into spoken words.",
    tags: [{ id: "images", name: "Image" }],
  },
  {
    id: 4,
    icon: "/images.png",
    title: "CSS Minifier",
    path: "https://cssminifier.com/",
    des: "Convert written text into spoken words.",
    tags: [{ id: "images", name: "Image" }],
  },
  {
    id: 5,
    icon: "/images.png",
    title: "JavaScript Beautifier",
    path: "https://beautifier.io/",
    des: "Convert written text into spoken words.",
    tags: [{ id: "images", name: "Image" }],
  },
  {
    id: 6,
    icon: "/file-pdf.png",
    title: "JSON Formatter",
    path: "https://jsonformatter.org/",
    des: "Convert written text into spoken words.",
    tags: [{ id: "pdfs", name: "PDFs" }],
  },
  {
    id: 7,
    icon: "/file-pdf.png",
    title: "Markdown Editor",
    path: "https://dillinger.io/",
    des: "Convert written text into spoken words.",
    tags: [{ id: "pdfs", name: "pdfs" }],
  },
  {
    id: 8,
    icon: "/document.png",
    title: "Regex Tester",
    path: "https://regex101.com/",
    des: "Convert written text into spoken words.",
    tags: [{ id: "documents", name: "documents" }],
  },
  {
    id: 9,
    icon: "/document.png",
    title: "Image Compressor",
    path: "https://tinypng.com/",
    des: "Convert written text into spoken words.",
    tags: [{ id: "documents", name: "documents" }],
  },
  {
    id: 10,
    icon: "/document.png",
    title: "Online Stopwatch",
    path: "https://www.online-stopwatch.com/",
    des: "Convert written text into spoken words.",
    tags: [{ id: "documents", name: "documents" }],
  },
  {
    id: 11,
    icon: "/document.png",
    title: "UUID Generator",
    path: "https://www.uuidgenerator.net/",
    des: "Convert written text into spoken words.",
    tags: [{ id: "documents", name: "documents" }],
  },
  {
    id: 12,
    icon: "/apps.png",
    title: "Lorem Ipsum Generator",
    path: "https://www.lipsum.com/",
    des: "Convert written text into spoken words.",
    tags: [{ id: "apps", name: "apps" }],
  },
  {
    id: 13,
    icon: "/apps.png",
    title: "Password Generator",
    path: "https://passwordsgenerator.net/",
    des: "Convert written text into spoken words.",
    tags: [{ id: "apps", name: "apps" }],
  },
  {
    id: 14,
    icon: "/apps.png",
    title: "Base64 Encoder/Decoder",
    path: "https://www.base64-image.de/",
    des: "Convert written text into spoken words.",
    tags: [{ id: "apps", name: "apps" }],
  },
  {
    id: 15,
    icon: "/file-zipper.png",
    title: "Unit Converter",
    path: "https://www.unitconverters.net/",
    des: "Convert written text into spoken words.",
    tags: [{ id: "compressed files", name: "compressed files" }],
  },
  {
    id: 16,
    icon: "/file-zipper.png",
    title: "Currency Converter",
    path: "https://www.xe.com/currencyconverter/",
    des: "Convert written text into spoken words.",
    tags: [{ id: "compressed files", name: "compressed files" }],
  },
  {
    id: 17,
    icon: "/play-alt.png",
    title: "IP Address Lookup",
    path: "https://www.whatismyip.com/",
    des: "Convert written text into spoken words.",
    tags: [{ id: "videos", name: "videos" }],
  },
  {
    id: 18,
    icon: "/play-alt.png",
    title: "Barcode Generator",
    path: "https://barcode.tec-it.com/",
    des: "Convert written text into spoken words.",
    tags: [{ id: "videos", name: "videos" }],
  },
  {
    id: 19,
    icon: "/music-file.png",
    title: "Text to Speech Converter",
    path: "https://ttsmp3.com/",
    des: "Convert written text into spoken words.",
    tags: [{ id: "audio", name: "audio" }],
  },
  {
    id: 20,
    icon: "/music-file.png",
    title: "Word Counter",
    path: "https://wordcounter.net/",
    des: "Convert written text into spoken words.",
    tags: [{ id: "audio", name: "audio" }],
  },
];
