export const extensions = [
  {
    id: 1,
    icon: "https://lh3.googleusercontent.com/lmKPPwyDZddSxT4DBtw9PsexjcVd1Ssw9P1nmOMbB9HlmPFebHgOBWHcDMYzISBmzmZWSXvQWUid3MMp5GbL2Xe4hA=s60",
    title: "QR Code Generator",
    path: "https://high-qr-code-generator.com/",
    des: "A super handy QR Code Generator / Creator for you.",
    tags: [
      { id: "ai", name: "AI" },
      { id: "audio", name: "Audio" },
    ],
    installDate: "2025/04/03",
    developerMode: true,
  },
  {
    id: 2,
    icon: "https://cdn-icons-png.flaticon.com/512/5968/5968292.png",
    title: "Color Palette Generator",
    path: "https://coolors.co/",
    des: "Generate perfect color combinations for your projects.",
    tags: [
      { id: "automation", name: "Automation" },
      { id: "book", name: "Book" },
    ],
    installDate: "2025-04-03",
    developerMode: true,
  },
  {
    id: 3,
    icon: "https://cdn-icons-png.flaticon.com/512/732/732212.png",
    title: "HTML Formatter",
    path: "https://htmlformatter.com/",
    des: "Beautify and format your HTML code instantly.",
    tags: [
      { id: "buy", name: "Buy" },
      { id: "community", name: "Community" },
    ],
    installDate: "2024-12-10",
    developerMode: true,
  },
  {
    id: 4,
    icon: "https://cdn-icons-png.flaticon.com/512/919/919832.png",
    title: "CSS Minifier",
    path: "https://cssminifier.com/",
    des: "Reduce the size of your CSS files quickly.",
    tags: [
      { id: "design", name: "Design" },
      { id: "directory", name: "Directory" },
    ],
    installDate: "2025-03-02",
    developerMode: true,
  },
  {
    id: 5,
    icon: "https://cdn-icons-png.flaticon.com/512/5968/5968292.png",
    title: "JavaScript Beautifier",
    path: "https://beautifier.io/",
    des: "Make your JavaScript code more readable and clean.",
    tags: [
      { id: "documentation", name: "Documentation" },
      { id: "engineering", name: "Engineering" },
    ],
    installDate: "2024-01-02",
    developerMode: true,
  },
  {
    id: 6,
    icon: "https://cdn-icons-png.flaticon.com/512/733/733609.png",
    title: "JSON Formatter",
    path: "https://jsonformatter.org/",
    des: "Format and validate your JSON data with ease.",
    tags: [
      { id: "documentation", name: "Documentation" },
      { id: "engineering", name: "Engineering" },
    ],
    installDate: "2024-01-06",
    developerMode: true,
  },
  {
    id: 7,
    icon: "https://cdn-icons-png.flaticon.com/512/281/281769.png",
    title: "Markdown Editor",
    path: "https://dillinger.io/",
    des: "Online markdown editor for writing and previewing markdown files.",
    tags: [
      { id: "buy", name: "Buy" },
      { id: "community", name: "Community" },
    ],
    installDate: "2023-01-02",
    developerMode: false,
  },
  {
    id: 8,
    icon: "https://cdn-icons-png.flaticon.com/512/919/919830.png",
    title: "Regex Tester",
    path: "https://regex101.com/",
    des: "Test and debug your regular expressions quickly.",
    tags: [
      { id: "buy", name: "Buy" },
      { id: "community", name: "Community" },
    ],
    installDate: "2024-11-02",
    developerMode: false,
  },
  {
    id: 9,
    icon: "https://cdn-icons-png.flaticon.com/512/732/732190.png",
    title: "Image Compressor",
    path: "https://tinypng.com/",
    des: "Compress images without losing quality.",
    tags: [
      { id: "ai", name: "AI" },
      { id: "audio", name: "Audio" },
    ],
    installDate: "2020-01-02",
    developerMode: false,
  },
  {
    id: 10,
    icon: "https://cdn-icons-png.flaticon.com/512/732/732200.png",
    title: "Online Stopwatch",
    path: "https://www.online-stopwatch.com/",
    des: "A simple online stopwatch for tracking time.",
    tags: [
      { id: "ai", name: "AI" },
      { id: "audio", name: "Audio" },
    ],
    installDate: "2024-08-04",
    developerMode: false,
  },
  {
    id: 11,
    icon: "https://cdn-icons-png.flaticon.com/512/732/732229.png",
    title: "UUID Generator",
    path: "https://www.uuidgenerator.net/",
    des: "Generate unique UUIDs instantly.",
    tags: [
      { id: "game", name: "Game" },
      { id: "health", name: "Health" },
    ],
    installDate: "2022-05-01",
    developerMode: false,
  },
  {
    id: 12,
    icon: "https://cdn-icons-png.flaticon.com/512/732/732216.png",
    title: "Lorem Ipsum Generator",
    path: "https://www.lipsum.com/",
    des: "Generate dummy text for testing and design.",
    tags: [
      { id: "game", name: "Game" },
      { id: "health", name: "Health" },
    ],
    installDate: "2021-09-12",
    developerMode: false,
  },
  {
    id: 13,
    icon: "https://cdn-icons-png.flaticon.com/512/732/732197.png",
    title: "Password Generator",
    path: "https://passwordsgenerator.net/",
    des: "Create strong and secure passwords.",
    tags: [
      { id: "game", name: "Game" },
      { id: "health", name: "Health" },
    ],
    installDate: "2024-01-02",
    developerMode: false,
  },
  {
    id: 14,
    icon: "https://cdn-icons-png.flaticon.com/512/732/732196.png",
    title: "Base64 Encoder/Decoder",
    path: "https://www.base64-image.de/",
    des: "Encode and decode Base64 data easily.",
    tags: [
      { id: "podcast", name: "Podcast" },
      { id: "research", name: "Research" },
    ],
    installDate: "2022-05-02",
    developerMode: false,
  },
  {
    id: 15,
    icon: "https://cdn-icons-png.flaticon.com/512/732/732211.png",
    title: "Unit Converter",
    path: "https://www.unitconverters.net/",
    des: "Convert between various units of measurement.",
    tags: [
      { id: "podcast", name: "Podcast" },
      { id: "research", name: "Research" },
    ],
    installDate: "2022-07-12",
    developerMode: false,
  },
  {
    id: 16,
    icon: "https://cdn-icons-png.flaticon.com/512/732/732203.png",
    title: "Currency Converter",
    path: "https://www.xe.com/currencyconverter/",
    des: "Convert currency values in real-time.",
    tags: [
      { id: "podcast", name: "Podcast" },
      { id: "research", name: "Research" },
    ],
    installDate: "2024-01-10",
    developerMode: false,
  },
  {
    id: 17,
    icon: "https://cdn-icons-png.flaticon.com/512/732/732215.png",
    title: "IP Address Lookup",
    path: "https://www.whatismyip.com/",
    des: "Find out your public IP address and details.",
    tags: [
      { id: "podcast", name: "Podcast" },
      { id: "research", name: "Research" },
    ],
    installDate: "2024-01-02",
    developerMode: false,
  },
  {
    id: 18,
    icon: "https://cdn-icons-png.flaticon.com/512/732/732208.png",
    title: "Barcode Generator",
    path: "https://barcode.tec-it.com/",
    des: "Create various types of barcodes online.",
    tags: [
      { id: "tutorial", name: "Tutorial" },
      { id: "video", name: "Video" },
    ],
    installDate: "2024-01-15",
    developerMode: false,
  },
  {
    id: 19,
    icon: "https://cdn-icons-png.flaticon.com/512/732/732227.png",
    title: "Text to Speech Converter",
    path: "https://ttsmp3.com/",
    des: "Convert written text into spoken words.",
    tags: [
      { id: "tutorial", name: "Tutorial" },
      { id: "video", name: "Video" },
    ],
    installDate: "2022-12-12",
    developerMode: false,
  },
  {
    id: 20,
    icon: "https://cdn-icons-png.flaticon.com/512/732/732228.png",
    title: "Word Counter",
    path: "https://wordcounter.net/",
    des: "Count words and characters in your text.",
    tags: [
      { id: "tutorial", name: "Tutorial" },
      { id: "video", name: "Video" },
    ],
    installDate: "2022-11-02",
    developerMode: false,
  },
];
